# Generated by Django 5.2.14 on 2026-05-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='vehicleprofile',
            new_name='vehicles_ve_user_id_24c28e_idx',
            old_name='vehicles_ve_user_id_9b901a_idx',
        ),
    ]
