# Generated by Django 5.2 on 2026-05-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.CharField(help_text='오피넷 주유소 고유 코드', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='주유소 상호명', max_length=100)),
                ('brand', models.CharField(help_text='정유사 상표 (SK, GS 등)', max_length=50)),
                ('address', models.CharField(help_text='주유소 도로명 주소', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='위도 (Y좌표)', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='경도 (X좌표)', max_digits=10)),
                ('gasoline_price', models.IntegerField(default=0, help_text='현재 휘발유 리터당 가격')),
                ('diesel_price', models.IntegerField(default=0, help_text='현재 경유 리터당 가격')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='유가 데이터 최종 업데이트 시각')),
            ],
        ),
    ]
