# Generated by Django 5.2.14 on 2026-05-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fuelprice',
            new_name='stations_fu_fuel_ty_788131_idx',
            old_name='stations_fu_fuel_ty_e56c8c_idx',
        ),
        migrations.RenameIndex(
            model_name='fuelprice',
            new_name='stations_fu_station_ec954b_idx',
            old_name='stations_fu_station_e29b10_idx',
        ),
        migrations.RenameIndex(
            model_name='gasstation',
            new_name='stations_ga_latitud_13053e_idx',
            old_name='stations_ga_latitud_1d5c86_idx',
        ),
        migrations.RenameIndex(
            model_name='gasstation',
            new_name='stations_ga_brand_333bfc_idx',
            old_name='stations_ga_brand_6f57a8_idx',
        ),
    ]
