# Generated by Codex on 2026-06-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="communitypost",
            name="community_c_station_884672_idx",
        ),
        migrations.RemoveField(
            model_name="communitypost",
            name="station",
        ),
    ]
