# Generated by Codex on 2026-06-24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("community", "0002_remove_station_from_community_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityPostBookmark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to="community.communitypost",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_post_bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="community_c_user_id_96b901_idx"),
                    models.Index(fields=["post", "-created_at"], name="community_c_post_id_50d05f_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "post"), name="unique_community_post_bookmark"),
                ],
            },
        ),
    ]
