# Generated by Django 5.2.14 on 2026-05-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=120)),
                ('issuer_name', models.CharField(blank=True, max_length=120)),
                ('discount_type', models.CharField(choices=[('per_liter', 'Per liter'), ('percentage', 'Percentage'), ('fixed_amount', 'Fixed amount')], default='per_liter', max_length=32)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('brand_scope', models.CharField(default='all', max_length=32)),
                ('min_payment_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('max_discount_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_discount_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_remaining_discount', models.PositiveIntegerField(blank=True, null=True)),
                ('card_image_url', models.URLField(blank=True)),
                ('source_url', models.URLField(blank=True, unique=True)),
                ('source_title', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('selenium', 'Selenium'), ('naver_search', 'Naver search'), ('issuer', 'Issuer'), ('admin_seed', 'Admin seed')], default='selenium', max_length=32)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('user_confirmed', 'User confirmed'), ('admin_verified', 'Admin verified')], default='unverified', max_length=32)),
                ('raw_summary', models.TextField(blank=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['issuer_name', 'card_name', 'id'],
            },
        ),
        migrations.RenameIndex(
            model_name='cardpolicy',
            new_name='cards_cardp_owner_i_8b05d3_idx',
            old_name='cards_cardp_owner_i_708547_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpolicy',
            new_name='cards_cardp_source__a67947_idx',
            old_name='cards_cardp_source__823a80_idx',
        ),
        migrations.RenameIndex(
            model_name='cardpolicy',
            new_name='cards_cardp_brand_s_883a54_idx',
            old_name='cards_cardp_brand_s_51f59d_idx',
        ),
        migrations.AlterField(
            model_name='cardbenefitsource',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('selenium', 'Selenium'), ('naver_search', 'Naver search'), ('issuer', 'Issuer'), ('admin_seed', 'Admin seed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='cardpolicy',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('selenium', 'Selenium'), ('naver_search', 'Naver search'), ('issuer', 'Issuer'), ('admin_seed', 'Admin seed')], default='manual', max_length=32),
        ),
        migrations.AddIndex(
            model_name='cardcatalog',
            index=models.Index(fields=['source_type', 'verification_status'], name='cards_cardc_source__37c78e_idx'),
        ),
        migrations.AddIndex(
            model_name='cardcatalog',
            index=models.Index(fields=['issuer_name', 'card_name'], name='cards_cardc_issuer__1c3b3f_idx'),
        ),
    ]
