# Generated by Django 5.2.14 on 2026-05-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardcatalog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardIngestionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', '대기 중'), ('PROCESSING', '수집 중'), ('SUCCESS', '수집 완료'), ('FAILED', '실패')], default='PENDING', max_length=20)),
                ('query', models.CharField(max_length=255)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('results', models.ManyToManyField(blank=True, to='cards.cardcatalog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
