# Generated by Django 5.2.15 on 2026-06-21 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_cardingestiontask"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardFuelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fuel_type", models.CharField(max_length=32)),
                (
                    "price_per_liter",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("collected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-collected_at", "fuel_type"],
            },
        ),
        migrations.RemoveField(
            model_name="cardcatalog",
            name="brand_scope",
        ),
        migrations.RemoveField(
            model_name="cardcatalog",
            name="discount_type",
        ),
        migrations.RemoveField(
            model_name="cardcatalog",
            name="discount_value",
        ),
        migrations.RemoveField(
            model_name="cardcatalog",
            name="max_discount_amount",
        ),
        migrations.RemoveField(
            model_name="cardcatalog",
            name="min_payment_amount",
        ),
        migrations.RemoveField(
            model_name="cardcatalog",
            name="monthly_discount_limit",
        ),
        migrations.RemoveField(
            model_name="cardcatalog",
            name="monthly_remaining_discount",
        ),
        migrations.AddField(
            model_name="cardpolicy",
            name="linked_catalog",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="linked_policies",
                to="cards.cardcatalog",
            ),
        ),
        migrations.AddField(
            model_name="cardpolicy",
            name="previous_month_spending",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="전월 실적 또는 이번 달 카드 사용액 (추천 알고리즘 Tier 매칭용)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cardbenefitsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("catalog", "Catalog"),
                    ("selenium", "Selenium"),
                    ("naver_search", "Naver search"),
                    ("issuer", "Issuer"),
                    ("admin_seed", "Admin seed"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="cardcatalog",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("catalog", "Catalog"),
                    ("selenium", "Selenium"),
                    ("naver_search", "Naver search"),
                    ("issuer", "Issuer"),
                    ("admin_seed", "Admin seed"),
                ],
                default="selenium",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="cardpolicy",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("catalog", "Catalog"),
                    ("selenium", "Selenium"),
                    ("naver_search", "Naver search"),
                    ("issuer", "Issuer"),
                    ("admin_seed", "Admin seed"),
                ],
                default="manual",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="CardBenefitTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        help_text="GASOLINE, DIESEL, LPG, EV, ALL 등", max_length=32
                    ),
                ),
                (
                    "min_performance_amount",
                    models.PositiveIntegerField(default=0, help_text="최소 전월 실적"),
                ),
                (
                    "max_performance_amount",
                    models.PositiveIntegerField(
                        blank=True, help_text="해당 혜택 상한 구간", null=True
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("per_liter", "Per liter"),
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed amount"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("brand_scope", models.CharField(default="all", max_length=32)),
                (
                    "min_payment_amount",
                    models.PositiveIntegerField(
                        blank=True, help_text="건당 최소 결제금액", null=True
                    ),
                ),
                (
                    "monthly_discount_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="월간 할인 한도", null=True
                    ),
                ),
                (
                    "card_catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit_tiers",
                        to="cards.cardcatalog",
                    ),
                ),
            ],
            options={
                "ordering": ["card_catalog", "fuel_type", "min_performance_amount"],
            },
        ),
    ]
